# Change these first
owner: TandemChat # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: API
    url: https://app.tandemchat.ru/api
  - name: Web
    url: https://app.tandemchat.ru
  - name: CDN
    url: https://app.tandemchat.ru/autumn
  - name: Voice
    url: https://vortex.rus-land.fun

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tandemchat.ru
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tandem
  introTitle: "**Tandem Status** позволяет узнать статус работы систем нашего сервиса."
  introMessage: Будьте в курсе статуса систем проекта
  navbar:
    - title: Статус
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
